apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: main
        image: eu.gcr.io/epam-15/cicd_app:__TAG__
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
